version: '3.2'

services:
  elasticsearch:
    labels:
      - "traefik.enable=true"
      - "traefik.port=9200"
      - "traefik.frontend.rule=Host:el.mous.ovh"
      - "traefik.docker.network=traefik-public"

  logstash:
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:minio.mous.ovh,minio1.mous.ovh"
      - "traefik.docker.network=traefik-public"

  kibana:
    networks:
      - elk
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.port=5601"
      - "traefik.frontend.rule=Host:kib.mous.ovh,kibana.mous.ovh"
      - "traefik.docker.network=traefik-public"

networks:
  elk:
    driver: bridge
  traefik-public:
    external: true

